"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminRouter = void 0;
const express_1 = require("express");
const auth_1 = require("../../middlewares/auth");
const admin_cities_routes_1 = require("../geo/admin-cities.routes");
const admin_parks_routes_1 = require("../geo/admin-parks.routes");
const admin_states_routes_1 = require("../geo/admin-states.routes");
const admin_guides_routes_1 = require("../guides/admin-guides.routes");
const admin_users_routes_1 = require("../users/admin-users.routes");
const admin_trails_routes_1 = require("../trails/admin-trails.routes");
const admin_media_routes_1 = require("../media/admin-media.routes");
const admin_expeditions_routes_1 = require("../expeditions/admin-expeditions.routes");
const admin_reservations_routes_1 = require("../reservations/admin-reservations.routes");
const admin_payments_routes_1 = require("../payments/admin-payments.routes");
const admin_dashboard_routes_1 = require("../dashboard/admin-dashboard.routes");
const admin_reviews_routes_1 = require("../reviews/admin-reviews.routes");
const router = (0, express_1.Router)();
router.use((0, auth_1.authenticate)());
router.use('/users', admin_users_routes_1.adminUsersRouter);
router.use('/guides', admin_guides_routes_1.adminGuidesRouter);
router.use('/states', admin_states_routes_1.adminStatesRouter);
router.use('/cities', admin_cities_routes_1.adminCitiesRouter);
router.use('/parks', admin_parks_routes_1.adminParksRouter);
router.use('/trails', admin_trails_routes_1.adminTrailsRouter);
router.use('/media', admin_media_routes_1.adminMediaRouter);
router.use('/expeditions', admin_expeditions_routes_1.adminExpeditionsRouter);
router.use('/reservations', admin_reservations_routes_1.adminReservationsRouter);
router.use('/payments', admin_payments_routes_1.adminPaymentsRouter);
router.use('/dashboard', admin_dashboard_routes_1.adminDashboardRouter);
router.use('/reviews', admin_reviews_routes_1.adminReviewsRouter);
exports.adminRouter = router;
//# sourceMappingURL=admin.routes.js.map